debug: true

proxy:
  coll: all
  enable_content_rewrite: false
  enable_banner: false
  enable_wombat: true

  ca_name: pywb OWT CA

# enable for recording
# below can be commented out if not recording
recorder: live

collections:
  live: $live

autoindex: 30
