version: '3.3'

services:
    shepherd:
        image: oldwebtoday/shepherd:1.2.5-beta.1
        environment:
            - BROWSER_NET=pywb-remote-browsers_browsers
            - PROXY_HOST=pywb
            - PROXY_PORT=8080
            # set to 1 to allow recording
            - ALLOW_RECORD=0

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./collections:/app/collections

        ports:
            - 9020:9020

    redis:
        image: redis:3.2.4
        networks:
            - browsers
            - default

    pywb:
        image: webrecorder/pywb:2.6.0b0
        networks:
            - browsers

        environment:
            - REDIS_URL=redis://redis/0
            - VOLUME_DIR=/app

        working_dir: /app

        volumes:
            - ./uwsgi.ini:/uwsgi/uwsgi.ini
            - ./rbsapp.py:/app/rbsapp.py
            - ./config.yaml:/app/config.yaml
            - ./collections:/app/collections

    coturn:
        image: oldwebtoday/coturn:1.0
        networks:
            - browsers
 
        ports:
            - "33478:33478/tcp"
            - "33478:33478/udp"

networks:
    default:
        driver: bridge

    browsers:
        driver: bridge
